---
sudo: required
language: python

services:
  - docker

install:
  - pip install "ome-ansible-molecule<0.5"

script:
  - molecule test -s $SCENARIO

env:
  - SCENARIO=newdep
  - SCENARIO=python3
  - SCENARIO=upgrade-py2py3
  - SCENARIO=upgradetovenv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
